// ============================================================
// SECTION 3 — MOCK AGENT BACKEND (unchanged)
// Emits the same event shape a real backend/orchestrator would:
// agent.task.assigned, task.started, task.progress, task.completed,
// task.failed. Swap this class for a RealAgentProvider later without
// touching any rendering code — nothing in three/ or ui/ knows this
// is mocked.
// ============================================================
export class MockAgentProvider {
  constructor(bus) {
    this.bus = bus;
    this._taskSeq = 1;
  }

  assignTask(agent, agentConfig, taskDef, params) {
    const task = {
      id: "t" + this._taskSeq++,
      agentId: agent.id,
      type: taskDef.id,
      title: taskDef.label,
      parameters: params,
      status: "queued",
      stage: "Assigned",
      createdAt: Date.now(),
      startedAt: null,
      completedAt: null,
      result: null,
      error: null,
    };
    this.bus.emit("agent.task.assigned", { agentId: agent.id, task });

    const prepDelay = 700 + Math.random() * 500;
    const workDelay = 2200 + Math.random() * 1800;
    const reviewDelay = 900 + Math.random() * 600;
    const willFail = Math.random() < 0.08;

    setTimeout(() => {
      task.status = "processing"; task.stage = "Preparing"; task.startedAt = Date.now();
      this.bus.emit("task.started", { agentId: agent.id, task: { ...task } });

      setTimeout(() => {
        task.stage = "Working";
        this.bus.emit("task.progress", { agentId: agent.id, task: { ...task } });

        setTimeout(() => {
          if (willFail) {
            task.status = "failed"; task.stage = "Error";
            task.error = pickErrorMessage();
            this.bus.emit("task.failed", { agentId: agent.id, task: { ...task } });
            return;
          }
          task.stage = "Reviewing";
          this.bus.emit("task.progress", { agentId: agent.id, task: { ...task } });

          setTimeout(() => {
            task.status = "completed"; task.stage = "Complete"; task.completedAt = Date.now();
            task.result = buildMockResult(agentConfig, taskDef, params);
            this.bus.emit("task.completed", { agentId: agent.id, task: { ...task } });
          }, reviewDelay);
        }, workDelay);
      }, prepDelay);
    }, 150);

    return task;
  }
}

function pickErrorMessage() {
  const msgs = [
    "Source data was incomplete — needs another input.",
    "Rate limit hit while calling an external tool.",
    "Task parameters were ambiguous — clarification needed.",
    "A downstream service timed out.",
  ];
  return msgs[Math.floor(Math.random() * msgs.length)];
}

function buildMockResult(agentConfig, taskDef, params) {
  const p = params || {};
  const vals = Object.keys(p).filter((k) => p[k]).map((k) => `${k}: ${p[k]}`).join("\n");
  const intros = {
    content: `Draft ready from Milo in the Creative Studio for "${taskDef.label}".`,
    research: `Findings compiled by Sage in the Research Lodge for "${taskDef.label}".`,
    data: `Analysis complete from Aria at the Analytics Station for "${taskDef.label}".`,
    automation: `Workflow "${taskDef.label}" finished running with Forge in the Workshop.`,
    manager: `Atlas prepared a Command Hall summary for "${taskDef.label}".`,
  };
  const intro = intros[agentConfig.id] || `Task "${taskDef.label}" complete.`;
  return `${intro}\n\nInputs used:\n${vals || "(none provided)"}\n\nThis is a mock result generated by the development backend. When connected to a real provider, this panel will show the actual AI output.`;
}
